package com.mybatis.mapper;

import com.mybatis.pojo.Dept;
import com.mybatis.pojo.DeptExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    Dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept1
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    int updateByPrimaryKey(Dept record);
}