package com.mybatis.mapper;

import com.mybatis.pojo.Emp;
import com.mybatis.pojo.EmpExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int insert(Emp record);
    //添加

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int insertSelective(Emp record);
    //选择性添加
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    Emp selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);
    //根据条件选择性修改
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);
    //根据条件修改
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp1
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    int updateByPrimaryKey(Emp record);
}