package com.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept1.dept_id
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept1.dept_name
     *
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept1.dept_id
     *
     * @return the value of dept1.dept_id
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept1.dept_id
     *
     * @param deptId the value for dept1.dept_id
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept1.dept_name
     *
     * @return the value of dept1.dept_name
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept1.dept_name
     *
     * @param deptName the value for dept1.dept_name
     * @mbggenerated Fri Nov 29 15:54:16 GMT+08:00 2024
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}