package com.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp1.emp_id
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp1.emp_name
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp1.age
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp1.gender
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp1.dept_id
     *
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp1.emp_id
     *
     * @return the value of emp1.emp_id
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp1.emp_id
     *
     * @param empId the value for emp1.emp_id
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp1.emp_name
     *
     * @return the value of emp1.emp_name
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp1.emp_name
     *
     * @param empName the value for emp1.emp_name
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp1.age
     *
     * @return the value of emp1.age
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp1.age
     *
     * @param age the value for emp1.age
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp1.gender
     *
     * @return the value of emp1.gender
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp1.gender
     *
     * @param gender the value for emp1.gender
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp1.dept_id
     *
     * @return the value of emp1.dept_id
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp1.dept_id
     *
     * @param deptId the value for emp1.dept_id
     * @mbggenerated Fri Nov 29 15:48:23 GMT+08:00 2024
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}